name: Ruby Gem(dmy)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.1
    - run: bundle install

    - name: Publish to RubyGems
      run: |
        git config --global user.name "siranovel"
        git config --global user.email "siranovel@gmail.com"
        bundle exec rake release
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
        OWNER: ${{ github.repository_owner }}
       GEM_HOST_OTP_CODE: ${{ github.event.inputs.rubygems-otp-code }} 
