name: Ruby Gem(dmy)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - run: bundle install

    - name: Publish to RubyGems
      run: |
        curl -u siranovel https://rubygems.org/api/v1/api_key.yaml > ~/.gem/credentials
        chmod 0600 ~/.gem/credentials
        gem build *.gemspec
    
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
