name: Ruby Gem(relese)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build + relese
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.10

    - name: Publish to RubyGems
      run: |
        gh release create "v0.2.0" --draft
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: ${{ steps.tag.outputs.name }}
        
